// Runs before `ng build` on Vercel.
// Reads BACKEND_URL from environment and writes it into environment.prod.ts
// so Angular bakes the correct API / Socket URL into the production bundle.
const fs   = require('fs');
const path = require('path');

const backendUrl = (process.env.BACKEND_URL || '').replace(/\/$/, ''); // trim trailing slash

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${backendUrl}/api',
  socketUrl: '${backendUrl}',
};
`;

const target = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(target, content, 'utf8');
console.log(`✅ environment.prod.ts written  (BACKEND_URL=${backendUrl || '(not set)'})`);
